<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-HL4JRJF" failures="2" tests="2" name="Default test(failed)" time="0.085" errors="0" timestamp="2022-09-08T19:36:04 IST">
  <testcase classname="com.qa.demo.RetryFailedDemo" name="test2" time="0.011">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.qa.demo.RetryFailedDemo.test2(RetryFailedDemo.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.qa.demo.RetryFailedDemo" name="test3" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.demo.RetryFailedDemo.test3(RetryFailedDemo.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="com.qa.demo.RetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
